### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by nwlambert** [mcirio/stochasitic_PM#3]
Just a list of tasks, maybe not the best place for them, but anyway,....

- [ ]  Make Bath class
- [ ]  Make pre-built bath property functions (including DL case)
- [ ]  Add generic fitting (from the old code)
- [ ]  Incorporate Raj's performance enhancements
- [ ]  Add tests (first jupyter based, then pytest)
- [ ]  Add fermionic baths
